# Generated by Django 5.2.17 on 2026-09-19 01:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('events', '0003_event_cancellation_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor_email', models.CharField(max_length=150)),
                ('action', models.CharField(choices=[('EVENT_PUBLISHED', 'Event Published'), ('EVENT_UNPUBLISHED', 'Event Unpublished'), ('EVENT_UPDATED', 'Event Updated'), ('EVENT_CANCELLED', 'Event Cancelled'), ('EVENT_SALES_PAUSED', 'Event Sales Paused'), ('EVENT_SALES_RESUMED', 'Event Sales Resumed'), ('EVENT_ANNOUNCED', 'Event Announced'), ('IMAGE_DELETED', 'Image Deleted'), ('ORDER_VOIDED', 'Order Voided'), ('ORDER_REFUND_MARKED', 'Order Refund Marked'), ('TICKETS_RESENT', 'Tickets Resent'), ('TICKET_VOIDED', 'Ticket Voided'), ('CHECKIN_UNDONE', 'Checkin Undone')], max_length=32)),
                ('target_type', models.CharField(blank=True, max_length=16)),
                ('target_id', models.UUIDField(blank=True, null=True)),
                ('target_label', models.CharField(blank=True, max_length=150)),
                ('reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='events.event')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='accounts.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', '-created_at'], name='common_audi_organiz_67d3d0_idx'), models.Index(fields=['event', '-created_at'], name='common_audi_event_i_04d12b_idx'), models.Index(fields=['target_type', 'target_id'], name='common_audi_target__65ba7e_idx')],
            },
        ),
    ]
