# Generated by Django 5.2.17 on 2026-09-19 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('EVENT_PUBLISHED', 'Event Published'), ('EVENT_UNPUBLISHED', 'Event Unpublished'), ('EVENT_UPDATED', 'Event Updated'), ('EVENT_CANCELLED', 'Event Cancelled'), ('EVENT_DELETED', 'Event Deleted'), ('EVENT_SALES_PAUSED', 'Event Sales Paused'), ('EVENT_SALES_RESUMED', 'Event Sales Resumed'), ('EVENT_ANNOUNCED', 'Event Announced'), ('IMAGE_DELETED', 'Image Deleted'), ('ORDER_VOIDED', 'Order Voided'), ('ORDER_REFUND_MARKED', 'Order Refund Marked'), ('TICKETS_RESENT', 'Tickets Resent'), ('TICKET_VOIDED', 'Ticket Voided'), ('CHECKIN_UNDONE', 'Checkin Undone')], max_length=32),
        ),
    ]
