# Generated by Django 5.2.17 on 2026-09-30 12:24

import apps.common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_auditlog_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=apps.common.models.site_logo_upload_path)),
                ('tagline', models.CharField(blank=True, max_length=160)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('whatsapp', models.CharField(blank=True, max_length=30)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('instagram_url', models.URLField(blank=True)),
                ('tiktok_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('complaints_book_url', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'configuración del sitio',
                'verbose_name_plural': 'configuración del sitio',
            },
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('EVENT_PUBLISHED', 'Event Published'), ('EVENT_UNPUBLISHED', 'Event Unpublished'), ('EVENT_UPDATED', 'Event Updated'), ('EVENT_CANCELLED', 'Event Cancelled'), ('EVENT_DELETED', 'Event Deleted'), ('EVENT_SALES_PAUSED', 'Event Sales Paused'), ('EVENT_SALES_RESUMED', 'Event Sales Resumed'), ('EVENT_ANNOUNCED', 'Event Announced'), ('IMAGE_DELETED', 'Image Deleted'), ('SITE_SETTINGS_UPDATED', 'Site Settings Updated'), ('ORDER_VOIDED', 'Order Voided'), ('ORDER_REFUND_MARKED', 'Order Refund Marked'), ('TICKETS_RESENT', 'Tickets Resent'), ('TICKET_VOIDED', 'Ticket Voided'), ('CHECKIN_UNDONE', 'Checkin Undone')], max_length=32),
        ),
    ]
