# Generated by Django 5.2.17 on 2026-09-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_site_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('EVENT_PUBLISHED', 'Event Published'), ('EVENT_UNPUBLISHED', 'Event Unpublished'), ('EVENT_UPDATED', 'Event Updated'), ('EVENT_CANCELLED', 'Event Cancelled'), ('EVENT_DELETED', 'Event Deleted'), ('EVENT_SALES_PAUSED', 'Event Sales Paused'), ('EVENT_SALES_RESUMED', 'Event Sales Resumed'), ('EVENT_ANNOUNCED', 'Event Announced'), ('IMAGE_DELETED', 'Image Deleted'), ('SITE_SETTINGS_UPDATED', 'Site Settings Updated'), ('ORDER_VOIDED', 'Order Voided'), ('ORDER_REFUND_MARKED', 'Order Refund Marked'), ('TICKETS_RESENT', 'Tickets Resent'), ('TICKET_VOIDED', 'Ticket Voided'), ('CHECKIN_UNDONE', 'Checkin Undone'), ('EMPLOYEE_CREATED', 'Employee Created'), ('EMPLOYEE_UPDATED', 'Employee Updated'), ('EMPLOYEE_DEACTIVATED', 'Employee Deactivated'), ('EMPLOYEE_REACTIVATED', 'Employee Reactivated'), ('EMPLOYEE_PASSWORD_RESET', 'Employee Password Reset'), ('EMPLOYEE_DELETED', 'Employee Deleted'), ('TICKET_CHECKED_IN', 'Ticket Checked In')], max_length=32),
        ),
    ]
