# Generated by Django 5.2.17 on 2026-10-03 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_document_type'),
        ('common', '0006_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('EVENT_PUBLISHED', 'Event Published'), ('EVENT_UNPUBLISHED', 'Event Unpublished'), ('EVENT_UPDATED', 'Event Updated'), ('EVENT_CANCELLED', 'Event Cancelled'), ('EVENT_DELETED', 'Event Deleted'), ('EVENT_SALES_PAUSED', 'Event Sales Paused'), ('EVENT_SALES_RESUMED', 'Event Sales Resumed'), ('EVENT_ANNOUNCED', 'Event Announced'), ('IMAGE_DELETED', 'Image Deleted'), ('SITE_SETTINGS_UPDATED', 'Site Settings Updated'), ('PAYMENT_SETTINGS_UPDATED', 'Payment Settings Updated'), ('ORDER_VOIDED', 'Order Voided'), ('ORDER_REFUND_MARKED', 'Order Refund Marked'), ('ORDER_MANUAL_SALE', 'Order Manual Sale'), ('TICKETS_RESENT', 'Tickets Resent'), ('TICKET_VOIDED', 'Ticket Voided'), ('CHECKIN_UNDONE', 'Checkin Undone'), ('GUEST_CODES_GENERATED', 'Guest Codes Generated'), ('GUEST_CODE_VOIDED', 'Guest Code Voided'), ('GUEST_CODE_REDEEMED', 'Guest Code Redeemed'), ('EMPLOYEE_CREATED', 'Employee Created'), ('EMPLOYEE_UPDATED', 'Employee Updated'), ('EMPLOYEE_DEACTIVATED', 'Employee Deactivated'), ('EMPLOYEE_REACTIVATED', 'Employee Reactivated'), ('EMPLOYEE_PASSWORD_RESET', 'Employee Password Reset'), ('EMPLOYEE_DELETED', 'Employee Deleted'), ('TICKET_CHECKED_IN', 'Ticket Checked In'), ('ORGANIZATION_CREATED', 'Organization Created'), ('ORGANIZATION_UPDATED', 'Organization Updated'), ('ORGANIZATION_DEACTIVATED', 'Organization Deactivated'), ('ORGANIZATION_REACTIVATED', 'Organization Reactivated'), ('ORGANIZER_CREATED', 'Organizer Created'), ('ORGANIZER_UPDATED', 'Organizer Updated'), ('ORGANIZER_DEACTIVATED', 'Organizer Deactivated'), ('ORGANIZER_REACTIVATED', 'Organizer Reactivated'), ('ORGANIZER_PASSWORD_RESET', 'Organizer Password Reset'), ('SESSIONS_REVOKED', 'Sessions Revoked')], max_length=32),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='accounts.organization'),
        ),
    ]
