# Generated by Django 5.2.17 on 2026-09-18 21:14

import apps.events.image_processing
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventimage',
            name='image',
            field=models.ImageField(upload_to=apps.events.image_processing.event_image_upload_path),
        ),
    ]
