# Generated by Django 5.2.17 on 2026-09-19 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_eventimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cancellation_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='cancellation_reason_code',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='event',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='sales_paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
