# Generated by Django 5.2.17 on 2026-09-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='eventimage',
            name='one_cover_image_per_event',
        ),
        migrations.AddField(
            model_name='eventimage',
            name='kind',
            field=models.CharField(choices=[('FLYER', 'Flyer'), ('ZONES', 'Zonas'), ('MAP', 'Mapa de ubicación')], default='FLYER', max_length=8),
        ),
        migrations.AddConstraint(
            model_name='eventimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_cover', True)), fields=('event', 'kind'), name='one_cover_image_per_event_kind'),
        ),
    ]
