# Generated by Django 5.2.17 on 2026-09-30 15:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_eventimage_kind'),
        ('orders', '0002_void_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_guest',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='GuestCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=16, unique=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('REDEEMED', 'Redimido'), ('VOIDED', 'Anulado')], default='AVAILABLE', max_length=12)),
                ('batch_id', models.UUIDField(db_index=True)),
                ('label', models.CharField(blank=True, max_length=80)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_codes_created', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_codes', to='events.event')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guest_code', to='orders.order')),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guest_codes', to='events.tickettype')),
            ],
            options={
                'ordering': ['-created_at', 'code'],
                'indexes': [models.Index(fields=['event', 'status'], name='orders_gues_event_i_498b0a_idx')],
            },
        ),
    ]
