# Generated by Django 5.2.17 on 2026-10-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_guest_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='gateway_order_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
