# Generated by Django 5.2.17 on 2026-10-02 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_gateway_order_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buyer_document_type',
            field=models.CharField(blank=True, choices=[('DNI', 'DNI'), ('CE', 'Carné de extranjería'), ('PASSPORT', 'Pasaporte')], max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='is_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='manual_payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Efectivo'), ('YAPE_PLIN', 'Yape / Plin'), ('TRANSFER', 'Transferencia'), ('OTHER', 'Otro')], max_length=12),
        ),
        migrations.AddField(
            model_name='order',
            name='sold_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='buyer_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='order',
            name='gateway',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
