# Generated by Django 5.2.17 on 2026-09-30 15:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_password_change_request'),
        ('events', '0004_eventimage_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='all_events',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='security_memberships', to='events.event'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Dueño'), ('STAFF', 'Personal'), ('SECURITY', 'Seguridad')], default='OWNER', max_length=16),
        ),
        migrations.CreateModel(
            name='RefreshTokenRotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jti', models.CharField(max_length=255, unique=True)),
                ('rotated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_rotations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
