# Generated by Django 5.2.17 on 2026-10-02 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_security_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='document_type',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
