# Generated by Django 5.2.17 on 2026-09-17 10:26

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('SESSION_CREATED', 'Sesión creada'), ('BROWSER_RETURN', 'Retorno del navegador'), ('IPN', 'Notificación de la pasarela'), ('MANUAL', 'Manual')], max_length=20)),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('signature_valid', models.BooleanField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_events', to='orders.order')),
            ],
            options={
                'ordering': ['-received_at'],
                'constraints': [models.UniqueConstraint(fields=('order', 'kind', 'external_id'), name='unique_payment_event_per_external_id')],
            },
        ),
    ]
