# Generated by Django 5.2.17 on 2026-10-02 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_paymentevent_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=32, unique=True)),
                ('enabled', models.BooleanField(default=False)),
                ('environment', models.CharField(choices=[('test', 'Pruebas'), ('production', 'Producción')], default='test', max_length=16)),
                ('credentials', models.TextField(blank=True)),
                ('hints', models.JSONField(blank=True, default=dict)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pasarela de pago',
                'verbose_name_plural': 'Pasarelas de pago',
            },
        ),
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('disabled', 'Deshabilitado'), ('fake', 'Simulador'), ('live', 'Pasarelas reales')], default='disabled', max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de pagos',
                'verbose_name_plural': 'Configuración de pagos',
            },
        ),
    ]
